# Generated by Django 4.0.3 on 2022-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nickname', models.CharField(max_length=8, verbose_name='닉네임')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='회원가입 시간')),
                ('divisions', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=8, verbose_name='부서')),
            ],
            options={
                'verbose_name': '계정',
                'verbose_name_plural': '계정',
                'db_table': 'user',
            },
        ),
    ]
